# Generated by Django 3.0.7 on 2020-12-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.TextField()),
                ('front', models.TextField()),
                ('back', models.TextField()),
                ('known', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
