# Generated by Django 3.1.4 on 2020-12-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(default='', max_length=20)),
                ('product_type', models.CharField(blank=True, default='', max_length=20)),
                ('free_tier', models.BooleanField(blank=True, default=False)),
                ('free_limit', models.CharField(blank=True, default='N/A', max_length=20)),
                ('link', models.CharField(default='/', max_length=40)),
                ('img_source', models.CharField(default='/static/Images/', max_length=60)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(default='', max_length=20)),
                ('product_type', models.CharField(blank=True, default='', max_length=20)),
                ('free_tier', models.BooleanField(blank=True, default=False)),
                ('free_limit', models.CharField(blank=True, default='N/A', max_length=20)),
                ('link', models.CharField(default='/', max_length=40)),
                ('img_source', models.CharField(default='/static/Images/', max_length=60)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Backend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(default='', max_length=20)),
                ('product_type', models.CharField(blank=True, default='', max_length=20)),
                ('free_tier', models.BooleanField(blank=True, default=False)),
                ('free_limit', models.CharField(blank=True, default='N/A', max_length=20)),
                ('link', models.CharField(default='/', max_length=40)),
                ('img_source', models.CharField(default='/static/Images/', max_length=60)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.TextField()),
                ('front', models.TextField()),
                ('back', models.TextField()),
                ('known', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cards',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(default='', max_length=20)),
                ('product_type', models.CharField(blank=True, default='', max_length=20)),
                ('free_tier', models.BooleanField(blank=True, default=False)),
                ('free_limit', models.CharField(blank=True, default='N/A', max_length=20)),
                ('link', models.CharField(default='/', max_length=40)),
                ('img_source', models.CharField(default='/static/Images/', max_length=60)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Frontend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(default='', max_length=20)),
                ('product_type', models.CharField(blank=True, default='', max_length=20)),
                ('free_tier', models.BooleanField(blank=True, default=False)),
                ('free_limit', models.CharField(blank=True, default='N/A', max_length=20)),
                ('link', models.CharField(default='/', max_length=40)),
                ('img_source', models.CharField(default='/static/Images/', max_length=60)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hosting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(default='', max_length=20)),
                ('product_type', models.CharField(blank=True, default='', max_length=20)),
                ('free_tier', models.BooleanField(blank=True, default=False)),
                ('free_limit', models.CharField(blank=True, default='N/A', max_length=20)),
                ('link', models.CharField(default='/', max_length=40)),
                ('img_source', models.CharField(default='/static/Images/', max_length=60)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=30)),
                ('body', models.TextField(default='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
