# Generated by Django 3.0.7 on 2020-12-06 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cards',
            options={'managed': False},
        ),
    ]
