# Generated by Django 3.1.4 on 2020-12-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='id',
        ),
        migrations.AlterField(
            model_name='note',
            name='user',
            field=models.CharField(default='', max_length=30, primary_key=True, serialize=False),
        ),
    ]
