# Generated by Django 3.0.7 on 2020-12-07 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20201206_1346'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cards',
            table='cards',
        ),
    ]
