# Generated by Django 3.0.7 on 2020-12-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20201206_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(default='', max_length=20)),
                ('product_type', models.CharField(default='', max_length=20)),
                ('free_tier', models.BooleanField(default=False)),
                ('free_limit', models.CharField(default='N/A', max_length=20)),
                ('link', models.CharField(default='/', max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(default='', max_length=20)),
                ('product_type', models.CharField(default='', max_length=20)),
                ('free_tier', models.BooleanField(default=False)),
                ('free_limit', models.CharField(default='N/A', max_length=20)),
                ('link', models.CharField(default='/', max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Backend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(default='', max_length=20)),
                ('product_type', models.CharField(default='', max_length=20)),
                ('free_tier', models.BooleanField(default=False)),
                ('free_limit', models.CharField(default='N/A', max_length=20)),
                ('link', models.CharField(default='/', max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(default='', max_length=20)),
                ('product_type', models.CharField(default='', max_length=20)),
                ('free_tier', models.BooleanField(default=False)),
                ('free_limit', models.CharField(default='N/A', max_length=20)),
                ('link', models.CharField(default='/', max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Frontend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(default='', max_length=20)),
                ('product_type', models.CharField(default='', max_length=20)),
                ('free_tier', models.BooleanField(default=False)),
                ('free_limit', models.CharField(default='N/A', max_length=20)),
                ('link', models.CharField(default='/', max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hosting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(default='', max_length=20)),
                ('product_type', models.CharField(default='', max_length=20)),
                ('free_tier', models.BooleanField(default=False)),
                ('free_limit', models.CharField(default='N/A', max_length=20)),
                ('link', models.CharField(default='/', max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
