# Generated by Django 3.0.7 on 2020-12-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_analytics_auth_backend_database_frontend_hosting'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytics',
            name='img_source',
            field=models.CharField(default='/static/Images/', max_length=20),
        ),
        migrations.AddField(
            model_name='auth',
            name='img_source',
            field=models.CharField(default='/static/Images/', max_length=20),
        ),
        migrations.AddField(
            model_name='backend',
            name='img_source',
            field=models.CharField(default='/static/Images/', max_length=20),
        ),
        migrations.AddField(
            model_name='database',
            name='img_source',
            field=models.CharField(default='/static/Images/', max_length=20),
        ),
        migrations.AddField(
            model_name='frontend',
            name='img_source',
            field=models.CharField(default='/static/Images/', max_length=20),
        ),
        migrations.AddField(
            model_name='hosting',
            name='img_source',
            field=models.CharField(default='/static/Images/', max_length=20),
        ),
    ]
