# Generated by Django 3.0.7 on 2020-12-07 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20201206_1849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cards',
            options={},
        ),
    ]
