# Generated by Django 3.1.4 on 2020-12-10 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20201210_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='known',
        ),
        migrations.RemoveField(
            model_name='cards',
            name='type',
        ),
    ]
