# Generated by Django 3.0.7 on 2020-12-07 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20201206_1855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cards',
            options={'managed': False},
        ),
    ]
