# Generated by Django 3.0.7 on 2020-12-07 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20201206_1856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cards',
            options={'managed': True},
        ),
    ]
