# Generated by Django 3.1.4 on 2020-12-10 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20201210_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='type',
            field=models.TextField(default=''),
        ),
    ]
