# Generated by Django 3.0.7 on 2020-12-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20201207_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytics',
            name='free_limit',
            field=models.CharField(blank=True, default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='free_tier',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='auth',
            name='free_limit',
            field=models.CharField(blank=True, default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='auth',
            name='free_tier',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='backend',
            name='free_limit',
            field=models.CharField(blank=True, default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='backend',
            name='free_tier',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='database',
            name='free_limit',
            field=models.CharField(blank=True, default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='database',
            name='free_tier',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='frontend',
            name='free_limit',
            field=models.CharField(blank=True, default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='frontend',
            name='free_tier',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='hosting',
            name='free_limit',
            field=models.CharField(blank=True, default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='hosting',
            name='free_tier',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
