# Generated by Django 3.1.4 on 2020-12-09 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20201207_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('title', models.CharField(max_length=30)),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='analytics',
            name='product_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='auth',
            name='product_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='backend',
            name='product_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='database',
            name='product_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='frontend',
            name='product_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='hosting',
            name='product_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
