# Generated by Django 3.1.4 on 2020-12-18 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20201213_1059'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
