# Generated by Django 3.1.4 on 2020-12-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='Auth',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='api',
            name='HTTPS',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='api',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='api',
            name='link',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='api',
            name='type',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='api',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
