# Generated by Django 3.1.4 on 2020-12-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20201224_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='link',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='api',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='api',
            name='type',
            field=models.CharField(default='', max_length=40),
        ),
    ]
