# Generated by Django 3.1.4 on 2020-12-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20201224_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='link',
            field=models.TextField(default=''),
        ),
    ]
