# Generated by Django 3.1.4 on 2020-12-24 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20201224_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('content', models.JSONField()),
            ],
        ),
    ]
